// <auto-generated />
using System;
using CourseSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourseSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230913084250_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CourseSystem.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("GradeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "67fb6788-21e9-403e-986f-e6e3dc205bca",
                            EmailConfirmed = false,
                            FirstName = "SUPER",
                            FullName = "SUPER ADMIN",
                            LastName = "ADMIN",
                            LockoutEnabled = false,
                            NormalizedUserName = "Y3I7152427U3JUA",
                            PasswordHash = "AQAAAAEAACcQAAAAEMJMhZzG5SgCUsnIPuy1mYdg6EYir551pdQ/xeZ6i1meKB7ad0bCu7jte7YVKHp+qQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4750bc6d-3669-440b-bf48-d56004c29cf2",
                            TwoFactorEnabled = false,
                            UserName = "Y3I7152427U3JUA"
                        },
                        new
                        {
                            Id = "a7936f4c-d172-43ef-a7e2-916c4b3ef9cf",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1ea19476-a633-416e-8c98-25e9f69c39fa",
                            EmailConfirmed = false,
                            FirstName = "Ogretmen",
                            FullName = "Ogretmen Deneme",
                            LastName = "Deneme",
                            LockoutEnabled = false,
                            NormalizedUserName = "OGRETMENDENEME",
                            PasswordHash = "AQAAAAEAACcQAAAAEByP9LyoFLm7CCrQdG6Qw/VZfp+pkJazOseQItmxHceYHRhUM4vi25ZHIWJtQaZ6IA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "cc6ee8ac-59bc-4439-aaac-55dae964d039",
                            TwoFactorEnabled = false,
                            UserName = "OgretmenDeneme"
                        },
                        new
                        {
                            Id = "bc651f10-6033-44ba-ad5d-db9495d56613",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "10fe67d1-d166-434e-8242-42ea4e1c3ea6",
                            EmailConfirmed = false,
                            FirstName = "Ogrenci",
                            FullName = "Ogrenci Deneme",
                            LastName = "Deneme",
                            LockoutEnabled = false,
                            NormalizedUserName = "OGRENCIDENEME",
                            PasswordHash = "AQAAAAEAACcQAAAAEBcl2y+1F3KxFid6u98pYfrvuNUCuDimedPl2wSQtIANtIc0vK+8TSzdNH2BZ9pESg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "151e05a5-933a-42a4-b20b-8bf7d51ae5b2",
                            TwoFactorEnabled = false,
                            UserName = "OgrenciDeneme"
                        },
                        new
                        {
                            Id = "d309c246-c6e9-4021-9f08-8206a00ed969",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2771c590-b087-4785-9d54-825002a89ade",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            FullName = "Admin Deneme",
                            LastName = "Deneme",
                            LockoutEnabled = false,
                            NormalizedUserName = "ADMINDENEME",
                            PasswordHash = "AQAAAAEAACcQAAAAEM1bN52EwRut/GtFViS65v17260idIIOWxZb0ffi706gkLUgd5i7EBv6TWyi43wC3g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "38b532bb-fdca-4c1b-9a9b-6af999d4a77b",
                            TwoFactorEnabled = false,
                            UserName = "AdminDeneme"
                        },
                        new
                        {
                            Id = "acf21fe8-eda6-4cde-a6f7-b4adc1507007",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1616393b-6ae2-463d-8d44-309255e462b4",
                            EmailConfirmed = false,
                            FirstName = "Misafir",
                            FullName = "Misafir Deneme",
                            LastName = "Deneme",
                            LockoutEnabled = false,
                            NormalizedUserName = "MISAFIRDENEME",
                            PasswordHash = "AQAAAAEAACcQAAAAEJJ3hkMUEAZCYoz+UVFnvCy3u2xLLGW6Fsy/DjC6FuBi2KVKWxKAV/eTPb0vUuuPwA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9608ec34-6292-4156-b44a-f57e96221829",
                            TwoFactorEnabled = false,
                            UserName = "MisafirDeneme"
                        });
                });

            modelBuilder.Entity("CourseSystem.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CourseSystem.Models.Content", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("HomeworkUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsHomework")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SlideUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("CourseSystem.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("CourseSystem.Models.CourseContent", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(1);

                    b.Property<Guid>("ContentId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(2);

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("CourseId", "ContentId");

                    b.HasIndex("ContentId");

                    b.ToTable("CourseContents");
                });

            modelBuilder.Entity("CourseSystem.Models.CourseGrade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CourseGradeName")
                        .HasColumnType("longtext");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("GradeId");

                    b.ToTable("CourseGrades");
                });

            modelBuilder.Entity("CourseSystem.Models.Grade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("CourseSystem.Models.TeacherCourse", b =>
                {
                    b.Property<string>("TeacherId")
                        .HasColumnType("varchar(255)")
                        .HasColumnOrder(1);

                    b.Property<Guid>("CourseGradeId")
                        .HasColumnType("char(36)")
                        .HasColumnOrder(2);

                    b.HasKey("TeacherId", "CourseGradeId");

                    b.HasIndex("CourseGradeId");

                    b.ToTable("TeacherCourses");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            ConcurrencyStamp = "c95b514c-1e82-4ba6-acd1-193fa807d184",
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        },
                        new
                        {
                            Id = "71805494-f543-40ad-b63e-870319d46db8",
                            ConcurrencyStamp = "b6250382-dfe6-4f38-9a16-03eca830f2cd",
                            Name = "Teacher",
                            NormalizedName = "TEACHER"
                        },
                        new
                        {
                            Id = "2bbf9a62-7592-45c5-9e08-97f817c9b3cc",
                            ConcurrencyStamp = "3b16d9a0-6c2c-4278-9861-e45e9708d32f",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        },
                        new
                        {
                            Id = "acbb1919-8c47-4be3-a4cb-c4198a65ca96",
                            ConcurrencyStamp = "ea109b8d-fae5-4b4f-8544-3be07f1def27",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "49a8f2dc-208c-48cb-bf49-82c25c0f9e38",
                            ConcurrencyStamp = "8598ad30-4065-44d2-a950-c43857ab8b56",
                            Name = "Guest",
                            NormalizedName = "GUEST"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            RoleId = "2c5e174e-3b0e-446f-86af-483d56fd7210"
                        },
                        new
                        {
                            UserId = "a7936f4c-d172-43ef-a7e2-916c4b3ef9cf",
                            RoleId = "71805494-f543-40ad-b63e-870319d46db8"
                        },
                        new
                        {
                            UserId = "bc651f10-6033-44ba-ad5d-db9495d56613",
                            RoleId = "2bbf9a62-7592-45c5-9e08-97f817c9b3cc"
                        },
                        new
                        {
                            UserId = "d309c246-c6e9-4021-9f08-8206a00ed969",
                            RoleId = "acbb1919-8c47-4be3-a4cb-c4198a65ca96"
                        },
                        new
                        {
                            UserId = "acf21fe8-eda6-4cde-a6f7-b4adc1507007",
                            RoleId = "49a8f2dc-208c-48cb-bf49-82c25c0f9e38"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("CourseSystem.Models.Course", b =>
                {
                    b.HasOne("CourseSystem.Models.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CourseSystem.Models.CourseContent", b =>
                {
                    b.HasOne("CourseSystem.Models.Content", "Content")
                        .WithMany("CourseContents")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseSystem.Models.Course", "Course")
                        .WithMany("CourseContents")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CourseSystem.Models.CourseGrade", b =>
                {
                    b.HasOne("CourseSystem.Models.Course", "Course")
                        .WithMany("CourseGrades")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseSystem.Models.Grade", "Grade")
                        .WithMany("CourseGrades")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("CourseSystem.Models.TeacherCourse", b =>
                {
                    b.HasOne("CourseSystem.Models.CourseGrade", "CourseGrade")
                        .WithMany("TeacherCourses")
                        .HasForeignKey("CourseGradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseSystem.Models.ApplicationUser", "Teacher")
                        .WithMany("TeacherCourses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseGrade");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CourseSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CourseSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CourseSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CourseSystem.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseSystem.Models.ApplicationUser", b =>
                {
                    b.Navigation("TeacherCourses");
                });

            modelBuilder.Entity("CourseSystem.Models.Category", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("CourseSystem.Models.Content", b =>
                {
                    b.Navigation("CourseContents");
                });

            modelBuilder.Entity("CourseSystem.Models.Course", b =>
                {
                    b.Navigation("CourseContents");

                    b.Navigation("CourseGrades");
                });

            modelBuilder.Entity("CourseSystem.Models.CourseGrade", b =>
                {
                    b.Navigation("TeacherCourses");
                });

            modelBuilder.Entity("CourseSystem.Models.Grade", b =>
                {
                    b.Navigation("CourseGrades");
                });
#pragma warning restore 612, 618
        }
    }
}
